spring:
  data:
    redis:
      port: 6380
      host: localhost
  config:
    activate:
      on-profile: local
  jpa:
    sql:
      init:
        mode: always
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL
    username: sa
    password:

oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    redirect-uri: http://localhost:3000/auth/kakao/callback
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me
    secret: ${KAKAO_CLIENT_SECRET}

